files:
  - source: /app/src/main/res/values/strings_l10n.xml
    translation: /app/src/main/res/values-%android_code%/strings_l10n.xml
    languages_mapping:
      android_code:
        lld: b+lld
        de: de
        it: it
