blank_issues_enabled: false
contact_links:
  - name: 💡 GitHub Discussions
    url: https://github.com/Benji377/Timety/discussions
    about: Ask questions, share your productivity setups, or discuss ideas with the community.
  - name: 📝 General Feedback
    url: https://tally.so/r/ODbEoA
    about: Share quick feedback directly with the developer via the Tally form.
