name: Test, Build and Release apk

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  build:
    name: Build APK
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '24'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml

    - name: Retrieve Flutter dependencies
      run: flutter pub get

    - name: Test Flutter build
      run: flutter test

    - name: Build debug APK
      run: flutter build apk --debug --split-per-abi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Android debug APK
        path: "build/app/outputs/apk/debug/*.apk"
      
