name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Hive Adapters
        run: dart run build_runner build --delete-conflicting-outputs

      # Build the APK (for direct installs/sideloading)
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      # Build the App Bundle (for Google Play Store)
      - name: Build App Bundle
        run: flutter build appbundle --release --no-tree-shake-icons

      - name: Rename Artifacts
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk timety-v${{ github.event.inputs.version }}.apk
          mv build/app/outputs/bundle/release/app-release.aab timety-v${{ github.event.inputs.version }}.aab

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: timety-release-builds
          path: |
            timety-v${{ github.event.inputs.version }}.apk
            timety-v${{ github.event.inputs.version }}.aab

  upload_to_release:
    name: Upload to GitHub Release
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [build]
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create attestation for build
        uses: actions/attest@v4
        with:
          subject-path: |
            artifacts/*.apk
            artifacts/*.aab

      - name: Release to GitHub
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
          name: Timety v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          files: |
            artifacts/*.apk
            artifacts/*.aab
